"""Generate a code map from the docs' own symbol citations.

Scans the same doc set as tests/test_doc_refs.py, collects every
`file.py:Symbol` anchor, and writes docs/CODE_MAP.md: a per-module table
of public/private symbols with the docs that cite them.

Usage:
    python3 scripts/generate_code_map.py [--out docs/CODE_MAP.md]
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from tests.test_doc_refs import _doc_files, collect_anchors  # noqa: E402

SYMBOL_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_.]*)")


def main() -> int:
    ap = argparse.ArgumentParser(description="Code map from doc citations")
    ap.add_argument("--out", type=str, default=str(ROOT / "docs" / "CODE_MAP.md"))
    args = ap.parse_args()

    anchors = collect_anchors()
    by_file: dict[str, dict[str, set[str]]] = defaultdict(lambda: defaultdict(set))
    for doc, rel_path, symbol in anchors:
        top = SYMBOL_RE.match(symbol)
        by_file[rel_path][top.group(1) if top else symbol].add(doc.relative_to(ROOT).as_posix())

    lines = [
        "# Code Map — Mamba-3-Lite",
        "",
        "> Auto-generated by `scripts/generate_code_map.py` from the docs'",
        "> `file.py:Symbol` citations. Regenerate after doc or code changes.",
        "",
        f"**{len(anchors)} anchors · {len(by_file)} modules**",
        "",
    ]
    for rel_path in sorted(by_file):
        lines.append(f"## `{rel_path}`")
        lines.append("")
        lines.append("| Symbol | Cited by |")
        lines.append("|---|---|")
        for sym in sorted(by_file[rel_path]):
            docs = ", ".join(f"`{d}`" for d in sorted(by_file[rel_path][sym]))
            lines.append(f"| `{sym}` | {docs} |")
        lines.append("")

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"[code-map] {len(anchors)} anchors → {out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
